Repository Day-Walk/BackEnd, pull requests merged in 2025-06, with the labels that each got.

#14 feat: 리뷰 관련 기능 구현
  src/main/java/com/day_walk/backend/domain/category/service/CategoryService.java
  src/main/java/com/day_walk/backend/domain/review/bean/DeleteReviewEntityBean.java
  src/main/java/com/day_walk/backend/domain/review/bean/GetReviewEntityBean.java
  src/main/java/com/day_walk/backend/domain/review/bean/SaveReviewEntityBean.java
  src/main/java/com/day_walk/backend/domain/review/controller/ReviewController.java
  src/main/java/com/day_walk/backend/domain/review/data/ReviewEntity.java
  src/main/java/com/day_walk/backend/domain/review/data/in/DeleteReviewDto.java
  src/main/java/com/day_walk/backend/domain/review/data/in/SaveReviewDto.java
  src/main/java/com/day_walk/backend/domain/review/data/out/GetReviewByPlaceDto.java
  src/main/java/com/day_walk/backend/domain/review/data/out/GetReviewByUserDto.java
  src/main/java/com/day_walk/backend/domain/review/data/out/GetReviewTotalDto.java
  src/main/java/com/day_walk/backend/domain/review/repository/ReviewRepository.java
  src/main/java/com/day_walk/backend/domain/review/service/ReviewService.java
  src/main/java/com/day_walk/backend/domain/sub_category/bean/GetSubCategoryEntityBean.java
  src/main/java/com/day_walk/backend/domain/tag/bean/GetTagBean.java
  src/main/java/com/day_walk/backend/domain/tag/bean/GetTagEntityBean.java
  src/main/java/com/day_walk/backend/domain/tag/repository/TagRepository.java
  src/main/java/com/day_walk/backend/domain/tag/service/TagService.java
  src/main/java/com/day_walk/backend/global/util/StringToUUIDListConverter.java
Labels: feature

#18 feat: error 관련 기능
  src/main/java/com/day_walk/backend/global/error/CustomException.java
  src/main/java/com/day_walk/backend/global/error/ErrorCode.java
  src/main/java/com/day_walk/backend/global/error/GlobalExceptionHandler.java
  src/main/java/com/day_walk/backend/global/error/ResponseErrorEntity.java
Labels: feature

#16 feat: 장소 찜 관련 기능
  src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceByLikeDto.java
  src/main/java/com/day_walk/backend/domain/place_like/bean/DeletePlaceLikeEntityBean.java
  src/main/java/com/day_walk/backend/domain/place_like/bean/GetPlaceLikeEntityBean.java
  src/main/java/com/day_walk/backend/domain/place_like/bean/SavePlaceLikeEntityBean.java
  src/main/java/com/day_walk/backend/domain/place_like/controller/PlaceLikeController.java
  src/main/java/com/day_walk/backend/domain/place_like/data/PlaceLikeEntity.java
  src/main/java/com/day_walk/backend/domain/place_like/data/in/DeletePlaceLikeDto.java
  src/main/java/com/day_walk/backend/domain/place_like/data/in/SavePlaceLikeDto.java
  src/main/java/com/day_walk/backend/domain/place_like/repository/PlaceLikeRepository.java
  src/main/java/com/day_walk/backend/domain/place_like/service/PlaceLikeService.java
Labels: feature

#19 feat: 코스 관련 기능 구현
  src/main/java/com/day_walk/backend/domain/course/bean/GetCourseEntityBean.java
  src/main/java/com/day_walk/backend/domain/course/bean/SaveCourseEntityBean.java
  src/main/java/com/day_walk/backend/domain/course/controller/CourseController.java
  src/main/java/com/day_walk/backend/domain/course/data/CourseEntity.java
  src/main/java/com/day_walk/backend/domain/course/data/dto/in/ChangeBooleanDto.java
  src/main/java/com/day_walk/backend/domain/course/data/dto/in/ModifyCourseTitleDto.java
  src/main/java/com/day_walk/backend/domain/course/data/dto/in/SaveCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/repository/CourseRepository.java
  src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
Labels: feature

#24 feat: 코스 조회 관련 기능
  src/main/java/com/day_walk/backend/domain/course/bean/GetAllCourseEntityBean.java
  src/main/java/com/day_walk/backend/domain/course/bean/GetSearchCourseEntityBean.java
  src/main/java/com/day_walk/backend/domain/course/bean/GetUsersAllCourseEntityBean.java
  src/main/java/com/day_walk/backend/domain/course/controller/CourseController.java
  src/main/java/com/day_walk/backend/domain/course/data/CourseEntity.java
  src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetAllCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetSearchCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetUsersAllCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/repository/CourseRepository.java
  src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
Labels: feature

#29 feat: 코스 조회 관련 기능 추가 작업
  src/main/java/com/day_walk/backend/domain/course/bean/GetSearchCourseEntityBean.java
  src/main/java/com/day_walk/backend/domain/course/bean/GetUsersAllCourseEntityBean.java
  src/main/java/com/day_walk/backend/domain/course/controller/CourseController.java
  src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetAllCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetSearchCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/data/dto/out/GetUsersAllCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
Labels: feature

#38 feat: 장소 상세 조회 로직 수정
  src/main/java/com/day_walk/backend/domain/place/controller/PlaceController.java
  src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceDto.java
  src/main/java/com/day_walk/backend/domain/place/service/PlaceService.java
  src/main/java/com/day_walk/backend/domain/place_like/bean/GetPlaceLikeEntityBean.java
  src/main/java/com/day_walk/backend/domain/place_like/controller/PlaceLikeController.java
  src/main/java/com/day_walk/backend/domain/place_like/repository/PlaceLikeRepository.java
  src/main/java/com/day_walk/backend/domain/place_like/service/PlaceLikeService.java
  src/main/java/com/day_walk/backend/domain/review/controller/ReviewController.java
Labels: feature

#48 feat: api 명세서 통일화
  src/main/java/com/day_walk/backend/BackendApplication.java
  src/main/java/com/day_walk/backend/domain/course/controller/CourseController.java
  src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
  src/main/java/com/day_walk/backend/domain/course_like/service/CourseLikeService.java
  src/main/java/com/day_walk/backend/domain/place/controller/PlaceController.java
  src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceBySearchDto.java
  src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceDto.java
  src/main/java/com/day_walk/backend/domain/place/service/PlaceService.java
  src/main/java/com/day_walk/backend/domain/place_like/bean/GetPlaceLikeEntityBean.java
  src/main/java/com/day_walk/backend/domain/place_like/controller/PlaceLikeController.java
  src/main/java/com/day_walk/backend/domain/place_like/data/in/DeletePlaceLikeDto.java
  src/main/java/com/day_walk/backend/domain/place_like/service/PlaceLikeService.java
  src/main/java/com/day_walk/backend/domain/review/data/out/GetReviewByUserDto.java
  src/main/java/com/day_walk/backend/domain/review/service/ReviewService.java
  src/main/java/com/day_walk/backend/global/error/ErrorCode.java
  src/main/resources/application.properties
Labels: feature

#50 feat: 회원가입 및 로그인 기능 구현 완료
  src/main/java/com/day_walk/backend/domain/user/bean/GetUserByKakaoIdBean.java
  src/main/java/com/day_walk/backend/domain/user/controller/UserController.java
  src/main/java/com/day_walk/backend/domain/user/data/UserEntity.java
  src/main/java/com/day_walk/backend/domain/user/data/UserRole.java
  src/main/java/com/day_walk/backend/domain/user/data/dto/in/SaveUserDto.java
  src/main/java/com/day_walk/backend/domain/user/data/dto/in/SignInUserDto.java
  src/main/java/com/day_walk/backend/domain/user/data/dto/out/GetUserBySignInDto.java
  src/main/java/com/day_walk/backend/domain/user/repository/UserRepository.java
  src/main/java/com/day_walk/backend/domain/user/service/UserService.java
Labels: feature

#52 feat: token 추가
  .gitignore
  build.gradle
  src/main/java/com/day_walk/backend/domain/user/controller/UserController.java
  src/main/java/com/day_walk/backend/domain/user/service/UserService.java
  src/main/java/com/day_walk/backend/global/config/WebSecurityConfig.java
  src/main/java/com/day_walk/backend/global/token/JwtAuthenticationFilter.java
  src/main/java/com/day_walk/backend/global/token/JwtUtil.java
  src/main/resources/application.properties
Labels: feature

#56 feat: add kafka
  .gitignore
  build.gradle
  src/main/java/com/day_walk/backend/BackendApplication.java
  src/main/java/com/day_walk/backend/domain/course/controller/CourseController.java
  src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
  src/main/java/com/day_walk/backend/domain/course_like/bean/GetCourseLikeEntityBean.java
  src/main/java/com/day_walk/backend/domain/course_like/bean/KafkaCourseLikeConsumer.java
  src/main/java/com/day_walk/backend/domain/course_like/controller/CourseLikeController.java
  src/main/java/com/day_walk/backend/domain/course_like/data/CourseLikeEntity.java
  src/main/java/com/day_walk/backend/domain/course_like/data/in/CourseLikeDto.java
  src/main/java/com/day_walk/backend/domain/course_like/data/in/SaveCourseLikeDto.java
  src/main/java/com/day_walk/backend/domain/course_like/repository/CourseLikeRedisRepository.java
  src/main/java/com/day_walk/backend/domain/course_like/service/CourseLikeService.java
  src/main/java/com/day_walk/backend/domain/place_like/bean/GetPlaceLikeEntityBean.java
  src/main/java/com/day_walk/backend/domain/place_like/bean/KafkaPlaceLikeConsumer.java
  src/main/java/com/day_walk/backend/domain/place_like/controller/PlaceLikeController.java
  src/main/java/com/day_walk/backend/domain/place_like/data/PlaceLikeEntity.java
  src/main/java/com/day_walk/backend/domain/place_like/data/in/DeletePlaceLikeDto.java
  src/main/java/com/day_walk/backend/domain/place_like/data/in/PlaceLikeDto.java
  src/main/java/com/day_walk/backend/domain/place_like/repository/PlaceLikeRedisRepository.java
  src/main/java/com/day_walk/backend/domain/place_like/service/PlaceLikeService.java
  src/main/java/com/day_walk/backend/global/config/KafkaCourseLikeConsumerConfig.java
  src/main/java/com/day_walk/backend/global/config/KafkaCourseLikeProducerConfig.java
  src/main/java/com/day_walk/backend/global/config/KafkaPlaceLikeConsumerConfig.java
  src/main/java/com/day_walk/backend/global/config/KafkaPlaceLikeProducerConfig.java
  src/main/java/com/day_walk/backend/global/config/RedisConfig.java
  src/main/java/com/day_walk/backend/global/config/WebSecurityConfig.java
  src/main/resources/application.properties
Labels: feature

#58 refactor: 로그인 로직 수정
  src/main/java/com/day_walk/backend/domain/user/data/UserEntity.java
  src/main/java/com/day_walk/backend/domain/user/service/UserService.java
Labels: refactor

#61 feat: S3 이미지 업로드 API 기능 구현 완료
  src/main/java/com/day_walk/backend/domain/category/controller/CategoryController.java
  src/main/java/com/day_walk/backend/domain/image/controller/ImageController.java
  src/main/java/com/day_walk/backend/domain/image/service/ImageService.java
  src/main/java/com/day_walk/backend/domain/user/data/dto/out/GetUserBySignInDto.java
  src/main/java/com/day_walk/backend/domain/user/service/UserService.java
Labels: feature

#66 feat: course-like 와 course 연결
  src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
  src/main/java/com/day_walk/backend/domain/course_like/bean/GetCourseLikeEntityBean.java
  src/main/java/com/day_walk/backend/domain/course_like/repository/CourseLikeRedisRepository.java
  src/main/java/com/day_walk/backend/domain/place/bean/GetPlaceEntityBean.java
  src/main/java/com/day_walk/backend/domain/place/controller/PlaceController.java
  src/main/java/com/day_walk/backend/domain/place/repository/PlaceRepository.java
  src/main/java/com/day_walk/backend/domain/place/service/PlaceService.java
  src/main/java/com/day_walk/backend/domain/place_like/bean/GetPlaceLikeEntityBean.java
  src/main/java/com/day_walk/backend/domain/place_like/repository/PlaceLikeRedisRepository.java
Labels: feature

#69 feat: course 상세조회 로직 수정
  src/main/java/com/day_walk/backend/domain/course/controller/CourseController.java
  src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
Labels: feature

#71 fix: 예외처리 수정
  src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
Labels: fix

#79 fix: null값 처리 추가
  src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceByLikeDto.java
  src/main/java/com/day_walk/backend/domain/place_like/repository/PlaceLikeRedisRepository.java
  src/main/java/com/day_walk/backend/domain/place_like/service/PlaceLikeService.java
Labels: fix

#82 feat: 장소 검색시 별점 추가
  src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceBySearchDto.java
  src/main/java/com/day_walk/backend/domain/place/service/PlaceService.java
Labels: feature

#84 refactor: prefix 추가
  src/main/java/com/day_walk/backend/domain/image/service/ImageService.java
Labels: refactor

#87 refactor: 유저별 리뷰 전체 조회에 plaeceId 추가
  src/main/java/com/day_walk/backend/domain/review/data/out/GetReviewByUserDto.java
Labels: refactor

#90 feat: 코스 상세 조회 로직 수정
  src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
Labels: feature

#92 feat: error 로직 수정
  src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
Labels: feature

#96 feat: search place add ml
  .gitignore
  src/main/java/com/day_walk/backend/domain/place/data/in/GetPlaceByMlDto.java
  src/main/java/com/day_walk/backend/domain/place/data/in/GetPlaceDetailByMlDto.java
  src/main/java/com/day_walk/backend/domain/place/data/in/GetPlaceListByMlDto.java
  src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceDto.java
  src/main/java/com/day_walk/backend/domain/place/service/PlaceService.java
  src/main/java/com/day_walk/backend/global/config/RestTemplateConfig.java
  src/main/resources/application.properties
Labels: feature

#98 feat: chatbot
  build.gradle
  src/main/java/com/day_walk/backend/domain/chat/controller/ChatController.java
  src/main/java/com/day_walk/backend/domain/chat/data/in/GetChatByMlDto.java
  src/main/java/com/day_walk/backend/domain/chat/data/in/SaveChatLogDto.java
  src/main/java/com/day_walk/backend/domain/chat/data/out/GetChatDto.java
  src/main/java/com/day_walk/backend/domain/chat/data/out/SaveChatDto.java
  src/main/java/com/day_walk/backend/domain/chat/service/ChatService.java
  src/main/java/com/day_walk/backend/domain/chat/service/SseEmitters.java
  src/main/java/com/day_walk/backend/domain/place/controller/PlaceController.java
  src/main/java/com/day_walk/backend/domain/place/data/in/GetPlaceDetailByMlDto.java
  src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceByChatDto.java
  src/main/java/com/day_walk/backend/domain/place/service/PlaceService.java
  src/main/java/com/day_walk/backend/global/config/SseClient.java
  src/main/java/com/day_walk/backend/global/config/kafka/KafkaCourseLikeConsumerConfig.java
  src/main/java/com/day_walk/backend/global/config/kafka/KafkaCourseLikeProducerConfig.java
  src/main/java/com/day_walk/backend/global/config/kafka/KafkaPlaceLikeConsumerConfig.java
  src/main/java/com/day_walk/backend/global/config/kafka/KafkaPlaceLikeProducerConfig.java
  src/main/java/com/day_walk/backend/global/error/CustomException.java
  src/main/java/com/day_walk/backend/global/error/ErrorCode.java
Labels: feature

#101 fix: 자료형 변경
  src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceDto.java
Labels: fix

#103 hotfix: 챗봇 응답 전송 완료시 커넥션 종료
  src/main/java/com/day_walk/backend/domain/chat/service/SseEmitters.java
  src/main/java/com/day_walk/backend/global/config/SseClient.java
Labels: fix

#105 hotfix: tagList에 converter 추가
  src/main/java/com/day_walk/backend/domain/user_like/data/UserLikeEntity.java
Labels: fix

#108 refactor: token header to cookie
  src/main/java/com/day_walk/backend/domain/course/data/CourseEntity.java
  src/main/java/com/day_walk/backend/domain/place/data/PlaceEntity.java
  src/main/java/com/day_walk/backend/domain/review/data/ReviewEntity.java
  src/main/java/com/day_walk/backend/domain/user/controller/UserController.java
  src/main/java/com/day_walk/backend/domain/user_like/data/UserLikeEntity.java
  src/main/java/com/day_walk/backend/global/config/WebSecurityConfig.java
  src/main/java/com/day_walk/backend/global/error/ErrorCode.java
  src/main/java/com/day_walk/backend/global/token/GenerateCookie.java
  src/main/java/com/day_walk/backend/global/token/JwtAuthenticationFilter.java
  src/main/java/com/day_walk/backend/global/token/JwtUtil.java
Labels: refactor

#114 fix: chatbot request, response 변경
  src/main/java/com/day_walk/backend/domain/chat/data/in/GetChatByMlDto.java
  src/main/java/com/day_walk/backend/domain/chat/data/out/GetChatDto.java
  src/main/java/com/day_walk/backend/domain/chat/service/SseEmitters.java
  src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceByChatDto.java
  src/main/java/com/day_walk/backend/global/config/SseClient.java
Labels: fix

#113 refactor: cors 설정 url 추가
  src/main/java/com/day_walk/backend/global/config/WebSecurityConfig.java
Labels: feature

#116 feat: click-log 저장 API 구현 완료
  src/main/java/com/day_walk/backend/domain/click_log/controller/ClickLogController.java
  src/main/java/com/day_walk/backend/domain/click_log/data/dto/in/SaveClickLogDto.java
  src/main/java/com/day_walk/backend/domain/click_log/service/ClickLogService.java
Labels: feature

#121 remove: 불필요한 패키지, import 제거
  src/main/java/com/day_walk/backend/domain/category/controller/CategoryController.java
  src/main/java/com/day_walk/backend/domain/category/data/out/GetCategoryDto.java
  src/main/java/com/day_walk/backend/domain/category/service/CategoryService.java
  src/main/java/com/day_walk/backend/domain/chat/controller/ChatController.java
  src/main/java/com/day_walk/backend/domain/chat/data/out/SaveChatDto.java
  src/main/java/com/day_walk/backend/domain/chat/service/ChatService.java
  src/main/java/com/day_walk/backend/domain/chat/service/SseEmitters.java
  src/main/java/com/day_walk/backend/domain/click_log/controller/ClickLogController.java
  src/main/java/com/day_walk/backend/domain/click_log/data/in/SaveClickLogDto.java
  src/main/java/com/day_walk/backend/domain/click_log/service/ClickLogService.java
  src/main/java/com/day_walk/backend/domain/course/controller/CourseController.java
  src/main/java/com/day_walk/backend/domain/course/data/CourseEntity.java
  src/main/java/com/day_walk/backend/domain/course/data/in/ChangeBooleanDto.java
  src/main/java/com/day_walk/backend/domain/course/data/in/ModifyCourseTitleDto.java
  src/main/java/com/day_walk/backend/domain/course/data/in/SaveCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/data/out/GetAllCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/data/out/GetCourseByLikeDto.java
  src/main/java/com/day_walk/backend/domain/course/data/out/GetCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/data/out/GetSearchCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/data/out/GetUsersAllCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
  src/main/java/com/day_walk/backend/domain/course_like/controller/CourseLikeController.java
  src/main/java/com/day_walk/backend/domain/course_like/repository/CourseLikeRedisRepository.java
  src/main/java/com/day_walk/backend/domain/course_like/service/CourseLikeService.java
  src/main/java/com/day_walk/backend/domain/image/controller/ImageController.java
  src/main/java/com/day_walk/backend/domain/image/service/ImageService.java
  src/main/java/com/day_walk/backend/domain/place/data/out/GetPlaceWithStarDto.java
  src/main/java/com/day_walk/backend/domain/place/service/PlaceService.java
  src/main/java/com/day_walk/backend/domain/place_like/service/PlaceLikeService.java
  src/main/java/com/day_walk/backend/domain/review/data/ReviewEntity.java
  src/main/java/com/day_walk/backend/domain/sub_category/data/SubCategoryEntity.java
  src/main/java/com/day_walk/backend/domain/user/bean/SaveUserBean.java
  src/main/java/com/day_walk/backend/domain/user/controller/UserController.java
  src/main/java/com/day_walk/backend/domain/user/data/UserEntity.java
  src/main/java/com/day_walk/backend/domain/user/data/in/SaveUserDto.java
  src/main/java/com/day_walk/backend/domain/user/data/in/SignInUserDto.java
  src/main/java/com/day_walk/backend/domain/user/data/in/UpdateUserDto.java
  src/main/java/com/day_walk/backend/domain/user/data/out/GetUserBySignInDto.java
  src/main/java/com/day_walk/backend/domain/user/data/out/GetUserDto.java
  src/main/java/com/day_walk/backend/domain/user/service/UserService.java
  src/main/java/com/day_walk/backend/domain/user_like/controller/UserLikeController.java
  src/main/java/com/day_walk/backend/domain/user_like/data/in/SaveCategoryListDto.java
  src/main/java/com/day_walk/backend/domain/user_like/data/in/SaveUserLikeDto.java
  src/main/java/com/day_walk/backend/domain/user_like/data/out/GetUserLikeDto.java
  src/main/java/com/day_walk/backend/domain/user_like/service/UserLikeService.java
  src/main/java/com/day_walk/backend/global/token/JwtUtil.java
Labels: refactor

#128 fix: 문제상황 수정
  src/main/java/com/day_walk/backend/domain/click_log/controller/ClickLogController.java
  src/main/java/com/day_walk/backend/domain/click_log/data/in/SaveClickLogDto.java
  src/main/java/com/day_walk/backend/domain/click_log/data/out/SaveClickLogByElkDto.java
  src/main/java/com/day_walk/backend/domain/click_log/service/ClickLogService.java
  src/main/java/com/day_walk/backend/domain/course/bean/GetAllCourseEntityBean.java
  src/main/java/com/day_walk/backend/domain/course/data/out/GetAllCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
  src/main/java/com/day_walk/backend/domain/review/service/ReviewService.java
Labels: fix

#146 feat: logout
  src/main/java/com/day_walk/backend/domain/user/controller/UserController.java
  src/main/java/com/day_walk/backend/global/token/GenerateCookie.java
  src/main/java/com/day_walk/backend/global/token/JwtAuthenticationFilter.java
Labels: feature

#145 feat: 코스 검색 By userName 기능 추가 완료
  src/main/java/com/day_walk/backend/domain/course/bean/GetSearchCourseEntityBean.java
  src/main/java/com/day_walk/backend/domain/course/data/out/GetCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/data/out/GetSearchCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/data/out/GetUsersAllCourseDto.java
  src/main/java/com/day_walk/backend/domain/course/repository/CourseRepository.java
  src/main/java/com/day_walk/backend/domain/course/service/CourseService.java
Labels: feature
